export const TOURNAMENTS_FETCH_REQUESTED = 'TOURNAMENTS/FETCH_REQUESTED';
export const TOURNAMENTS_FETCH_SUCCEEDED = 'TOURNAMENTS/FETCH_SUCCEEDED';
export const TOURNAMENTS_FETCH_FAILED = 'TOURNAMENTS/FETCH_FAILED';

export const TOURNAMENTS_ADD = 'TOURNAMENTS/ADD';
export const TOURNAMENTS_ADD_REQUESTED = 'TOURNAMENTS/ADD_REQUESTED';
export const TOURNAMENTS_ADD_SUCCEEDED = 'TOURNAMENTS/ADD_SUCCEEDED';
export const TOURNAMENTS_ADD_FAILED = 'TOURNAMENTS/ADD_FAILED';

export const TOURNAMENTS_EDIT = 'TOURNAMENTS/EDIT';
export const TOURNAMENTS_EDIT_REQUESTED = 'TOURNAMENTS/EDIT_REQUESTED';
export const TOURNAMENTS_EDIT_SUCCEEDED = 'TOURNAMENTS/EDIT_SUCCEEDED';
export const TOURNAMENTS_EDIT_FAILED = 'TOURNAMENTS/EDIT_FAILED';

export const TOURNAMENTS_DELETE = 'TOURNAMENTS/DELETE';
export const TOURNAMENTS_DELETE_REQUESTED = 'TOURNAMENTS/DELETE_REQUESTED';
export const TOURNAMENTS_DELETE_SUCCEEDED = 'TOURNAMENTS/DELETE_SUCCEEDED';
export const TOURNAMENTS_DELETE_FAILED = 'TOURNAMENTS/DELETE_FAILED';

export const TOURNAMENTS_UPDATE_UI_STATUS = 'TOURNAMENTS/UPDATE_UI_STATUS';
